web:
 image: silintl/php7
 ports:
  - "8000:80"
  - "8443:443"
 volumes:
  - $PWD:/var/www/html
  - $PWD/config/10-opcache.ini:/etc/php/7.0/apache2/conf.d/10-opcache.ini
  - $PWD/config/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
 links:
  - db:db
  - redis:redis
  - postfix:postfix
db:
 image: mysql
 volumes:
  - $PWD/data:/var/lib/mysql
 environment:
  MYSQL_ROOT_PASSWORD: root
 expose:
  - "3306"
 ports:
  - "3306:3306"
redis:
 image: redis
 ports:
  - "6379:6379"
postfix:
 image: catatnight/postfix
 environment:
  maildomain: mail.example.com
  smtp_user: user:pwd
 ports:
  - "225:25"