web:
 image: pablofmorales/apache-php7
 ports:
  - "9000:80"
  - "8443:443"
 volumes:
  - $PWD:/var/www/html
 links:
  - db:db
db:
 image: mysql
 volumes:
  - $PWD/data:/var/lib/mysql
 environment:
  MYSQL_ROOT_PASSWORD: root